# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_ViWxH39Kjl7x7xSyx4s2PBJdTGrTZR
"""

!pip install requests



import requests
from bs4 import BeautifulSoup
import smtplib

url="https://www.amazon.in/Apple-iPhone-13-128GB-Product/dp/B09G99CW2N/ref=sr_1_2_sspa?crid=CYWBMDOJG8XV&dib=eyJ2IjoiMSJ9.XqEI3jFpzXkt1EB1X4u2LTfRae_WYjAoQ87jOQJj3nUm4dNwa2HNimSIR7rIdyzE2mk8eMQpCyP0rSJeeGc_RohPGNsAtQk4u1iS5pwRcLtov9WQxIeTYUZyBownAFJnwsZh5OXtDmPakiyiD1VJWlIQ2x1Ja1eoyvbLorLU9JljC5msh2b-m2s0DYmwDKsnb0Pn8fc9LFNH0KxHQ9UkCf9P1o2c20V99P5B6OdhAkQ.JOl4qhKZkTmpYtuuO4PyqQpCXVkLIJJWKH6AdJ1fbks&dib_tag=se&keywords=iphone+15+pro+max&qid=1714492184&sprefix=iph%2Caps%2C434&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1"

headers = {"user agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"}

page=requests.get(url,headers=headers)

soup=BeautifulSoup(page.content,'html.parser')

print(soup.prettify())

print(soup.title)

#title of the page
print(soup.title)

print(soup.p)

print(soup.p)

print(soup.p.get_text())



!pip install selenium

!pip install bs4

!pip install pandas

!pip install Autoscraper

flipkart=''
amazon=''

def flipkart(name):
    try:
        global flipkart
        name1 = name.replace(" ","+")
        flipkart=f'https://www.flipkart.com/search?q={name1}&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off'
        res = requests.get(f'https://www.flipkart.com/search?q={name1}&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off',headers=headers)


        print("\nSearching in flipkart....")
        soup = BeautifulSoup(res.text,'html.parser')

        if(soup.select('._4rR01T')):
            flipkart_name = soup.select('._4rR01T')[0].getText().strip().upper()
            if name.upper() in flipkart_name:
                flipkart_price = soup.select('._30jeq3')[0].getText().strip()
                flipkart_name = soup.select('._4rR01T')[0].getText().strip()
                print("Flipkart:")
                print(flipkart_name)
                print(flipkart_price)
                print("---------------------------------")

        elif(soup.select('.s1Q9rs')):
            flipkart_name = soup.select('.s1Q9rs')[0].getText().strip()
            flipkart_name = flipkart_name.upper()
            if name.upper() in flipkart_name:
                flipkart_price = soup.select('._30jeq3')[0].getText().strip()
                flipkart_name = soup.select('.s1Q9rs')[0].getText().strip()
                print("Flipkart:")
                print(flipkart_name)
                print(flipkart_price)
                print("---------------------------------")
        else:
            flipkart_price='0'

        return flipkart_price
    except:
        print("Flipkart: No product found!")
        print("---------------------------------")
        flipkart_price= '0'
    return flipkart_price

def amazon(name):
    try:
        global amazon
        name1 = name.replace(" ","-")
        name2 = name.replace(" ","+")
        amazon=f'https://www.amazon.in/{name1}/s?k={name2}'
        res = requests.get(f'https://www.amazon.in/{name1}/s?k={name2}',headers=headers)
        print("\nSearching in amazon...")
        soup = BeautifulSoup(res.text,'html.parser')
        amazon_page = soup.select('.a-color-base.a-text-normal')
        amazon_page_length = int(len(amazon_page))
        for i in range(0,amazon_page_length):
            name = name.upper()
            amazon_name = soup.select('.a-color-base.a-text-normal')[i].getText().strip().upper()
            if name in amazon_name:
                amazon_name = soup.select('.a-color-base.a-text-normal')[i].getText().strip()
                amazon_price = soup.select('.a-price-whole')[i].getText().strip().upper()
                print("Amazon:")
                print(amazon_name)
                print("₹"+amazon_price)
                print("---------------------------------")
                break
            else:
                i+=1
                i=int(i)
                if i==amazon_page_length:
                    amazon_price = '0'
                    print("amazon : No product found!")
                    print("-----------------------------")
                    break

        return amazon_price
    except:
        print("Amazon: No product found!")
        print("---------------------------------")
        amazon_price = '0'
    return amazon_price

def convert(a):
    b=a.replace(" ",'')
    c=b.replace("INR",'')
    d=c.replace(",",'')
    f=d.replace("₹",'')
    g=int(float(f))
    return g

name=input("Product Name:\n")
flipkart_price=flipkart(name)
amazon_price=amazon(name)


if flipkart_price=='0':
    print("Flipkart: No product found!")
    flipkart_price = int(flipkart_price)
else:
    print("\nFlipkart Price:",flipkart_price)
    flipkart_price=convert(flipkart_price)
if amazon_price=='0':
    print("Amazon: No product found!")
    amazon_price = int(amazon_price)
else:
    print("\nAmazon price: ₹",amazon_price)
    amazon_price=convert(amazon_price)